#!/usr/bin/env bash
# generate-prompt-index.sh — parse all prompt files and write docs/PROMPT_INDEX.md
# v0.5.0

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODES_DIR="$REPO_ROOT/prompts/modes"
PACKS_DIR="$REPO_ROOT/prompts/packs"
CORE_FILE="$REPO_ROOT/prompts/atlas-one.md"
OUTPUT="$REPO_ROOT/docs/PROMPT_INDEX.md"
VERSION_FILE="$REPO_ROOT/VERSION"

VERSION=$(cat "$VERSION_FILE" 2>/dev/null | tr -d '[:space:]' || echo "unknown")
GENERATED_AT=$(date -u +"%Y-%m-%d")

extract_field() {
  local file="$1"
  local field="$2"
  grep "^${field}:" "$file" 2>/dev/null | head -1 | sed "s/^${field}:[[:space:]]*//" | xargs
}

extract_first_use_case() {
  local file="$1"
  grep "^Use when" "$file" 2>/dev/null | head -1 | sed 's/^Use when //' | sed 's/\.$//'
}

echo "Generating $OUTPUT …"

{
  cat <<HEADER
# Atlas One — Prompt Index

Version: $VERSION
Generated: $GENERATED_AT

This index is auto-generated by \`scripts/generate-prompt-index.sh\`.
Do not edit manually — run the script to regenerate.

---

## Core

| File | Version | Tags |
|------|---------|------|
HEADER

  if [[ -f "$CORE_FILE" ]]; then
    ver=$(extract_field "$CORE_FILE" "Version") || ver="—"
    tags=$(extract_field "$CORE_FILE" "Tags") || tags="—"
    echo "| [atlas-one.md](../prompts/atlas-one.md) | ${ver:-—} | ${tags:-—} |"
  fi

  cat <<MODES_HEADER

---

## Modes

| Mode | Use case | Version | Tags |
|------|----------|---------|------|
MODES_HEADER

  for f in "$MODES_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    name=$(basename "$f" .md)
    title=$(grep "^# " "$f" | head -1 | sed 's/^# //')
    ver=$(extract_field "$f" "Version") || ver="—"
    tags=$(extract_field "$f" "Tags") || tags="—"
    use_case=$(extract_first_use_case "$f") || use_case="—"
    echo "| [${title:-$name}](../prompts/modes/$name.md) | ${use_case:-—} | ${ver:-—} | ${tags:-—} |"
  done

  cat <<PACKS_HEADER

---

## Prompt Packs

| Pack | Use case | Version | Tags | Export |
|------|----------|---------|------|--------|
PACKS_HEADER

  for f in "$PACKS_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    name=$(basename "$f" .md)
    title=$(grep "^# " "$f" | head -1 | sed 's/^# //')
    ver=$(extract_field "$f" "Version") || ver="—"
    tags=$(extract_field "$f" "Tags") || tags="—"
    use_case=$(grep "^Use this pack" "$f" | head -1 | sed 's/^Use this pack //' | sed 's/\.$//' | xargs) || use_case="—"
    export_link="[.txt](../exports/prompt-packs/$name.txt)"
    echo "| [${title:-$name}](../prompts/packs/$name.md) | ${use_case:-—} | ${ver:-—} | ${tags:-—} | $export_link |"
  done

  cat <<EXPORTS_HEADER

---

## Exports

| File | Format | Use |
|------|--------|-----|
| [atlas-one-core.txt](../exports/atlas-one-core.txt) | Plain text | Paste into any AI assistant |
| [atlas-one-core.md](../exports/atlas-one-core.md) | Markdown | Link or import |
| [atlas-one-chatgpt-instructions.txt](../exports/atlas-one-chatgpt-instructions.txt) | Plain text | ChatGPT Custom Instructions |
| [atlas-one-claude-instructions.md](../exports/atlas-one-claude-instructions.md) | Markdown | Claude Project Instructions |
| [atlas-one-manifest.json](../exports/atlas-one-manifest.json) | JSON | Machine-readable prompt index |

---

*Run \`scripts/generate-prompt-index.sh\` to regenerate this file.*
EXPORTS_HEADER

} > "$OUTPUT"

echo "Done — wrote $OUTPUT"
